import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<header className="w-full flex justify-end p-4">
  <nav className="space-x-6 text-amber-300 font-semibold">
    <a href="#home" className="hover:underline">Home</a>
    <a href="#rsvp" className="hover:underline">RSVP</a>
    <a href="#about" className="hover:underline">About</a>
    <a href="#wedding" className="hover:underline">Wedding</a>
    <a href="#contact" className="hover:underline">Contact</a>
  </nav>
</header>

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
